---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  playbook: tests/testkitchen.yml
  hosts: localhost
  extra_vars:
    threatstack_deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
    <% if ENV['TS_NO_CONFIG_AGENT']  %>
    threatstack_configure_agent: false
    <% end %>
    threatstack_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>
    <% if ENV['TS_PACKAGE_VERSION'] %>
    # Should be in form threatstack-version=<version>.  ex. threatstack-version=1.4.4.0ubuntu14.0
    threatstack_pkg: <%= ENV['TS_PACKAGE_VERSION'] %>
    <% end %>
    <% if ENV['TS_RULE_SETS'] %>
    threatstack_ruleset: "<%= ENV['TS_RULE_SETS'] %>"
    <% end %>
    <% if ENV['TS_HOSTNAME'] %>
    threatstack_hostname: "<%= ENV['TS_HOSTNAME'] %>"
    <% end %>
    <% if ENV['TS_URL'] %>
    threatstack_url: "<%= ENV['TS_URL'] %>"
    <% end %>
    <% if ENV['TS_URL'] %>
    threatstack_feature_plan: "<%= ENV['TS_FEATURE_PLAN'] %>"
    <% end %>


platforms:
  - name: centos-7.5
    transport:
      max_ssh_sessions: 6
  - name: debian-8.11
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
