---
- name: Ensure ThreatStack dependencies are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-apt
      - apt-transport-https

- name: Add ThreatStack apt repository key
  apt_key:
    url: "{{ threatstack_url }}/APT-GPG-KEY-THREATSTACK"
    id: 6EE04BD4
    validate_certs: "{{ threatstack_pkg_validate | bool }}"

- name: Add Ubuntu ThreatStack apt repository
  apt_repository:
    repo: "deb {{ threatstack_pkg_url }}/Ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when:
    - when dry_run is undefined

- name: Add Ubuntu ThreatStack apt repository dry run
  apt_repository:
    repo: "deb {{ threatstack_pkg_url }} {{ ansible_distribution_release }} {{package_branch}}"
    state: present
    update_cache: yes
  when:
    - when dry_run is defined

- name: Ensure 2.x is installed when no version specified
  set_fact:
    threatstack_pkg: threatstack-agent=2*
  when:
    - not threatstack_v1
    - threatstack_pkg == 'threatstack-agent'

- name: Ensure ThreatStack latest is installed
  apt:
    name: "{{ threatstack_pkg }}"